name = "machine"
version = "0.1.0"

# default is 50 milliseconds
interval = 50

cli = "bun"

[new]
using = "wasm-pack"

[[crates]]
name = "machine-wasm"
link = true
target = "web"
out-dir = "pkg"

[crates.watch]
profile = "release"
